-- PART A2: Seed all products from flowers.ts using UPSERT
INSERT INTO public.ipf_products (product_key, name, category, unit, price, is_active, in_stock, todays_available)
VALUES
  -- Loose Flowers
  ('arali-pink', 'Arali (Pink Ganneu)', 'Loose Flowers', 'per bunch', 12.00, true, true, true),
  ('button-rose-red', 'Button Rose Red', 'Loose Flowers', 'per bunch', 10.00, true, true, true),
  ('button-rose-yellow', 'Button Rose Yellow', 'Loose Flowers', 'per bunch', 10.00, true, true, true),
  ('jasmine-loose', 'Jasmin(Malle) Loose', 'Loose Flowers', 'per bunch', 12.00, true, true, true),
  ('jathi-loose', 'Jathi Loose (Pink Jasmin)', 'Loose Flowers', 'per bunch', 10.00, true, true, true),
  ('mullai-loose', 'Mullai Loose (Jaji)', 'Loose Flowers', 'per bunch', 12.00, true, true, true),
  ('tuberose', 'Lily (Tuberose)', 'Loose Flowers', 'per bunch', 12.00, true, true, true),
  -- Leaves
  ('banana-leaves', 'Banana Leaves', 'Leaves', 'per leaf', 2.00, true, true, true),
  ('betel-leaves', 'Betel Leaves', 'Leaves', 'per bunch', 2.00, true, true, true),
  -- Strings
  ('jasmine-string', 'Jasmin String', 'Strings', 'per string', 17.00, true, true, true),
  ('mullai-string', 'Mullai String (Jaji or Pink Jasmine)', 'Strings', 'per string', 17.00, true, true, true),
  ('jathi-string', 'Jathi String', 'Strings', 'per string', 17.00, true, true, true),
  -- Special Flowers
  ('lotus-padma', 'Lotus (Padma)', 'Special Flowers', 'per piece', 2.00, true, true, true),
  -- Garlands (pre-order, price 0)
  ('garland-lotus', 'Lotus Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-rose', 'Jasmine & Rose Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-multicolor', 'Multicolor Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-red-yellow-rose', 'Red & Yellow Rose Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-lotus-jasmine', 'Lotus & Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-colorful', 'Colorful Rose & Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-red-rose', 'Classic Jasmine Red Rose Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-rose-gold', 'Jasmine Rose Gold Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-lotus-red', 'Lotus Red Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-red-classic', 'Classic Red Rose & Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-sunset-rose', 'Sunset Rose Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-yellow', 'Jasmine & Yellow Rose Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-rainbow-rose', 'Rainbow Rose Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-lotus-pair', 'Jasmine Lotus Pair Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-red-purple', 'Red & Purple Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-lotus-red', 'Premium Lotus Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-pink-band', 'Jasmine Pink Band Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-full-red', 'Full Red Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-pink-white', 'Pink & White Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-red-white-band', 'Red & White Band Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-rose-premium', 'Premium Jasmine Rose Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-purple-yellow', 'Purple & Yellow Rose Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-red-lotus-center', 'Red Jasmine Lotus Center Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-red-white-pattern', 'Red & White Pattern Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-lotus-premium', 'Premium Jasmine Lotus Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-lotus-red-small', 'Compact Lotus Red Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-lotus-elegant', 'Elegant Jasmine Lotus Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-red-lotus-long', 'Long Red Lotus Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-orange-jasmine', 'Orange Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-lotus-double', 'Double Jasmine Lotus Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-colorful-rose-long', 'Long Colorful Rose Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-lotus-hanging', 'Jasmine Lotus Hanging Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-red-lotus-classic', 'Classic Red Lotus Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-pink-white-spiral', 'Pink & White Spiral Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-red-yellow-jasmine', 'Red & Yellow Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-lotus-collection', 'Lotus Collection Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-temple-multicolor', 'Temple Multicolor Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-yellow-purple', 'Jasmine Yellow Purple Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-red-white-simple', 'Simple Red & White Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-wedding-jasmine-gold', 'Wedding Jasmine Gold Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-wedding-set', 'Wedding Set Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-magenta-orange', 'Magenta & Orange Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-jasmine-rose-set', 'Jasmine Rose Set Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-orange-rose-jasmine', 'Orange Rose Jasmine Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-lotus-pink-long', 'Long Lotus Pink Garland', 'Garlands', 'per pair', 0, true, true, true),
  ('garland-magenta-yellow-rose', 'Magenta & Yellow Rose Garland', 'Garlands', 'per pair', 0, true, true, true)
ON CONFLICT (product_key) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  unit = EXCLUDED.unit,
  price = EXCLUDED.price;